// Category keywords — match against deal title AND category field
// Since most deals have category "Today's Deal", we need title-based matching
export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  'Electronics': ['electronics', 'computer', 'laptop', 'tablet', 'phone', 'iphone', 'samsung', 'speaker', 'headphone', 'earbuds', 'airpods', 'smart home', 'amazon device', 'fire tv', 'kindle', 'echo', 'ring', 'camera', 'tv', 'monitor', 'charger', 'cable', 'bluetooth', 'wireless', 'usb', 'hdmi', 'power bank', 'battery', 'portable', 'mouse', 'keyboard', 'gaming', 'controller', 'nintendo', 'switch', 'playstation', 'xbox', 'console', 'router', 'wifi', 'projector', 'soundbar', 'dolby', 'rechargeable', 'smart watch', 'fitbit', 'garmin', 'gopro', 'drone', 'printer', 'hard drive', 'ssd', 'adapter', 'hub', 'dock', 'surge protector', 'power strip', 'led strip', 'smart plug', 'smart bulb', 'ring doorbell', 'security camera', 'dash cam'],
  'Home & Kitchen': ['home', 'kitchen', 'furniture', 'lamp', 'light', 'shelf', 'rack', 'organizer', 'mattress', 'bedding', 'pillow', 'towel', 'cleaning', 'cleaner', 'vacuum', 'appliance', 'tool', 'garden', 'outdoor', 'decor', 'curtain', 'rug', 'carpet', 'blender', 'mixer', 'coffee', 'toaster', 'microwave', 'air fryer', 'instant pot', 'cookware', 'pan', 'pot', 'knife', 'cutting board', 'storage', 'container', 'trash', 'laundry', 'detergent', 'soap', 'candle', 'diffuser', 'humidifier', 'fan', 'heater', 'filter', 'cordless', 'dewalt', 'mop', 'broom', 'hose', 'grill', 'patio', 'umbrella', 'shower', 'table', 'chair', 'desk', 'couch', 'bed frame', 'dresser', 'mirror', 'closet', 'hangers', 'iron', 'steamer', 'paper towel', 'plate', 'bowl', 'cup', 'mug', 'bottle', 'thermos', 'lunch box', 'wreath'],
  'Beauty': ['beauty', 'skin', 'skincare', 'hair', 'makeup', 'cosmetic', 'lotion', 'serum', 'shampoo', 'conditioner', 'face', 'facial', 'nail', 'lipstick', 'mascara', 'perfume', 'fragrance', 'moisturizer', 'sunscreen', 'spf', 'cream', 'oil', 'cleanser', 'toner', 'mask', 'concealer', 'foundation', 'blush', 'bronzer', 'eyeliner', 'eyeshadow', 'brush set', 'curling iron', 'flat iron', 'straightener', 'blow dryer', 'hair dryer', 'trimmer', 'razor', 'electric shaver', 'cologne', 'deodorant', 'body wash', 'body lotion', 'hand cream', 'lip balm', 'vitamin c', 'retinol', 'hyaluronic', 'collagen', 'bioderma', 'olaplex', 'cerave', 'neutrogena', 'powder'],
  'Fashion': ['fashion', 'clothing', 'shirt', 'dress', 'pant', 'jeans', 'shorts', 'jacket', 'coat', 'hoodie', 'sweater', 'shoes', 'sneaker', 'boot', 'sandal', 'slipper', 'hat', 'cap', 'beanie', 'watch', 'jewelry', 'necklace', 'bracelet', 'earring', 'sunglasses', 'bag', 'backpack', 'purse', 'wallet', 'belt', 'scarf', 'gloves', 'socks', 'underwear', 'leggings', 'swim', 'bikini', 'polo', 'blazer', 'nike', 'adidas', 'puma', 'new balance', 'under armour', 'champion', 'crocs'],
  'Toys': ['toy', 'doll', 'lego', 'playset', 'puzzle', 'board game', 'baby', 'infant', 'kids', 'stroller', 'car seat', 'diaper', 'wipes', 'formula', 'pacifier', 'crib', 'highchair', 'monster high', 'barbie', 'hot wheels', 'nerf', 'play-doh', 'action figure', 'stuffed animal', 'plush', 'coloring', 'crayon', 'marker', 'arts and crafts', 'building blocks', 'remote control', 'pretend play', 'costume', 'easter', 'egg decorat'],
  'Sports': ['sport', 'fitness', 'gym', 'yoga', 'exercise', 'bike', 'bicycle', 'cycling', 'outdoor', 'camping', 'tent', 'sleeping bag', 'hiking', 'fishing', 'golf', 'dumbbell', 'barbell', 'weight', 'kettlebell', 'resistance band', 'treadmill', 'protein', 'water bottle', 'cooler', 'kayak', 'skateboard', 'scooter', 'helmet', 'basketball', 'football', 'soccer', 'baseball', 'tennis', 'running', 'compression', 'foam roller', 'massage gun', 'travel'],
  'Pet Supplies': ['pet', 'dog', 'cat', 'puppy', 'kitten', 'leash', 'collar', 'harness', 'treat', 'kibble', 'litter', 'cat tree', 'scratching', 'chew toy', 'fetch', 'crate', 'carrier', 'aquarium', 'fish', 'bird', 'flea', 'tick', 'grooming', 'nail clipper', 'paw', 'food bowl', 'water fountain', 'training pad'],
};
